### ISSUE TITLE
Connection Squalit / Callpoppy

### ISSUE THREAD

**Issue by user1007017** [tipichris/Squalit#1]
After experimenting quite some hours I can't get it to work. 

After Squalit's export it reports it in the log file but no records are in the db.
I have added a record by hand, but callpoppy isn't showing the name.
Also resetting the database has no effect on the manually added record.

Which permissions are needed for the sqlite db?
What could cause this behaviour?

I'm using debian linux. Callpoppy works fine.

**Comment by tipichris** [comment]
There's not a huge amount of information to go on there. Can you try [setting the log level to 5](http://www.oak-wood.co.uk/oss/squalit#advancedopts) and see if anything useful is produced?

I wonder if squalit is not exporting to the place you expect it to. The default is `~/.callpoppy/callpoppy.db`. If you use Thunderbird's advanced config editor the current location is in `extensions.squalit.dbfile`. The format for this setting is tricky, see https://developer.mozilla.org/en-US/Add-ons/Code_snippets/File_I_O

Both Squalit and Callpoppy will normally run as the current user so the database should be owned by the current user, who must have read and write permissions

**Comment by user1007017** [comment]
Problem solved!!!
I had installed sqlite instead of sqlite3 which caused the faulty behaviour of squalit and callpoppy

As I read the error "file is encrypted or is not a database" I checked the sourcecode and saw it came from the db.
Then I started searching and read that sqlite3 is the standard since 10 years.

So removed sqlite and installed sqlite3 and everything works perfectly...
This information should be clarified in the readme...

...callPopPy expects to find a SQLite3 database at...

 ii  sqlite         2.8.17-7     amd64        command line interface for SQLite
 ii  sqlite3       3.7.13-1+deb7u1    amd64              Command line interface for SQLite 3
